"""initial schema

Revision ID: 72acaac80383
Revises:
Create Date: 2026-09-06 03:25:00.016531+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72acaac80383"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
        sa.UniqueConstraint("source", "external_id", name=op.f("uq_books_source_external_id")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fcm_token", sa.Text(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_push_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("fcm_token", name=op.f("uq_devices_fcm_token")),
    )
    op.create_table(
        "fsrs_params",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("desired_retention", sa.Float(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fsrs_params")),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("rows_seen", sa.Integer(), nullable=False),
        sa.Column("rows_new", sa.Integer(), nullable=False),
        sa.Column("rows_updated", sa.Integer(), nullable=False),
        sa.Column("rows_removed", sa.Integer(), nullable=False),
        sa.Column("cards_generated", sa.Integer(), nullable=False),
        sa.Column("cost_microusd", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_table(
        "writer_guidance",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("guidance", sa.Text(), nullable=False),
        sa.Column("basis", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_writer_guidance")),
    )
    op.create_table(
        "curated_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingest_run_id", sa.Integer(), nullable=False),
        sa.Column("curated_text", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingest_run_id"],
            ["ingest_runs.id"],
            name=op.f("fk_curated_units_ingest_run_id_ingest_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curated_units")),
    )
    op.create_table(
        "highlights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("chapter", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("personal_note", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("highlighted_at", sa.Date(), nullable=False),
        sa.Column("export_position", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_highlights_book_id_books")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_highlights")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_highlights_dedupe_key")),
    )
    op.create_table(
        "push_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("card_ids", sa.JSON(), nullable=False),
        sa.Column("due_count", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_push_runs_device_id_devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_runs")),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("original_front", sa.Text(), nullable=False),
        sa.Column("original_back", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("suspended_until", sa.DateTime(), nullable=True),
        sa.Column("generation_rounds", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("guidance_version", sa.Integer(), nullable=True),
        sa.Column("cost_microusd", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["guidance_version"],
            ["writer_guidance.version"],
            name=op.f("fk_cards_guidance_version_writer_guidance"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["curated_units.id"], name=op.f("fk_cards_unit_id_curated_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_table(
        "curated_unit_highlights",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("highlight_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["highlight_id"],
            ["highlights.id"],
            name=op.f("fk_curated_unit_highlights_highlight_id_highlights"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["curated_units.id"],
            name=op.f("fk_curated_unit_highlights_unit_id_curated_units"),
        ),
        sa.PrimaryKeyConstraint("unit_id", "highlight_id", name=op.f("pk_curated_unit_highlights")),
    )
    op.create_table(
        "card_state",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due", sa.DateTime(), nullable=False),
        sa.Column("last_review", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_card_state_card_id_cards")
        ),
        sa.PrimaryKeyConstraint("card_id", name=op.f("pk_card_state")),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("ingest_run_id", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("round", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("request", sa.JSON(), nullable=True),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_microusd", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], name=op.f("fk_llm_calls_card_id_cards")),
        sa.ForeignKeyConstraint(
            ["ingest_run_id"],
            ["ingest_runs.id"],
            name=op.f("fk_llm_calls_ingest_run_id_ingest_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["curated_units.id"], name=op.f("fk_llm_calls_unit_id_curated_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("rated_at", sa.DateTime(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=False),
        sa.Column("scheduled_days", sa.Integer(), nullable=False),
        sa.Column("state_before", sa.String(length=16), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_review_logs_card_id_cards")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_review_logs_device_id_devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_logs")),
        sa.UniqueConstraint("card_id", "rated_at", name=op.f("uq_review_logs_card_id_rated_at")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_logs")
    op.drop_table("llm_calls")
    op.drop_table("card_state")
    op.drop_table("curated_unit_highlights")
    op.drop_table("cards")
    op.drop_table("push_runs")
    op.drop_table("highlights")
    op.drop_table("curated_units")
    op.drop_table("writer_guidance")
    op.drop_table("ingest_runs")
    op.drop_table("fsrs_params")
    op.drop_table("devices")
    op.drop_table("books")
    # ### end Alembic commands ###
