#!/usr/bin/env python3
"""Generate the Recally launcher icon assets from the vendored font.

The committed XML is the asset — this script exists so the geometry can be
regenerated deliberately, not so the build can re-render it. See
docs/design/design-system.md, "Icon".

    python3 docs/design/icon/build_icon.py

Writes the five vector files next to this script; copy them into
android/app/src/main/res/ (drawable/ and mipmap-anydpi-v26/).
"""

import math
import pathlib
import re

from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = pathlib.Path(__file__).resolve().parent
FONT = HERE.parents[2] / "android/app/src/main/res/font/inter_tight_extrabold.ttf"

CANVAS = 108.0          # adaptive-icon viewport
MASK_RADIUS = 36.0      # circular mask radius from centre
PARALLAX = 4.0          # launcher parallax headroom
LETTER_HEIGHT = 46.0    # solved against MASK_RADIUS - PARALLAX; see the doc
GAP = 5.3               # recall gap, ~1.2px at 24dp
PRIMARY = "#1F6F5C"


def glyph_path(target_height: float) -> tuple[str, float]:
    """Return the R outline scaled to `target_height`, centred on its ink box."""
    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord("R")]

    from fontTools.pens.boundsPen import BoundsPen

    bounds = BoundsPen(glyphs)
    glyphs[name].draw(bounds)
    x_min, y_min, x_max, y_max = bounds.bounds

    scale = target_height / (y_max - y_min)
    width = (x_max - x_min) * scale

    # Centre the INK box on the canvas, not the advance width: the R's right
    # sidebearing would otherwise push it visibly left of centre.
    centre = CANVAS / 2
    transform = Transform(
        scale, 0, 0, -scale,
        centre - width / 2 - x_min * scale,
        centre + target_height / 2 + y_min * scale,
    )

    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}")
    glyphs[name].draw(TransformPen(pen, transform))
    return pen.getCommands(), width


def check_safe_zone(width: float, height: float) -> None:
    """The ink box's furthest corner must clear the mask even under parallax."""
    corner = math.hypot(width / 2, height / 2)
    limit = MASK_RADIUS - PARALLAX
    if corner > limit:
        raise SystemExit(
            f"letter too large: corner {corner:.2f} exceeds {limit:.2f} "
            f"(mask {MASK_RADIUS} less {PARALLAX} parallax)"
        )
    print(f"  safe zone ok: corner {corner:.2f} <= {limit:.2f}")


def clipped_groups(path: str, gap_top: float, gap_bottom: float, viewport: float) -> str:
    """Draw the letter twice, clipped above and below the gap.

    VectorDrawable has no mask element, so the gap cannot be a knockout rect.
    Editing one group without the other silently desyncs the mark.
    """
    return f"""
    <group>
        <clip-path android:pathData="M0,0h{viewport:g}v{gap_top:.2f}h-{viewport:g}z" />
        <path
            android:fillColor="#FFFFFF"
            android:pathData="{path}" />
    </group>

    <group>
        <clip-path android:pathData="M0,{gap_bottom:.2f}h{viewport:g}v{viewport - gap_bottom:.2f}h-{viewport:g}z" />
        <path
            android:fillColor="#FFFFFF"
            android:pathData="{path}" />
    </group>
"""


def vector(body: str, size: float, comment: str) -> str:
    return f"""{comment}
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size:g}dp"
    android:height="{size:g}dp"
    android:viewportWidth="{size:g}"
    android:viewportHeight="{size:g}">
{body}</vector>
"""


def rescale(path: str, factor: float) -> str:
    return re.sub(r"-?\d+\.?\d*", lambda m: f"{float(m.group()) * factor:.2f}", path)


def main() -> None:
    path, width = glyph_path(LETTER_HEIGHT)
    check_safe_zone(width, LETTER_HEIGHT)

    gap_top = CANVAS / 2 - GAP / 2
    gap_bottom = gap_top + GAP
    print(f"  gap {GAP} at y {gap_top:.2f}..{gap_bottom:.2f} "
          f"({GAP * 24 / CANVAS:.2f}px at 24dp)")

    shared = f"""<!--
  Recally launcher icon — {{role}}.
  Inter Tight ExtraBold "R", outlines extracted from the vendored TTF
  (app/src/main/res/font/inter_tight_extrabold.ttf), centred on its ink box
  rather than its advance width, and sized so the furthest corner stays
  inside the circular mask even under launcher parallax.

  The horizontal gap at y={gap_top:.2f}..{gap_bottom:.2f} is the "recall gap": the letter
  is partly forgotten and the eye completes it.

  Generated by docs/design/icon/build_icon.py — the path IS the asset; do
  not re-render it from a font at build time.
  Geometry and rationale: docs/design/design-system.md, "Icon".
-->"""

    groups = clipped_groups(path, gap_top, gap_bottom, CANVAS)

    (HERE / "ic_launcher_foreground.xml").write_text(
        vector(groups, CANVAS, shared.format(role="foreground layer")))

    (HERE / "ic_launcher_monochrome.xml").write_text(
        vector(groups, CANVAS, shared.format(
            role="monochrome layer for Android 13 themed icons")))

    (HERE / "ic_launcher_background.xml").write_text(vector(
        f'    <path\n        android:fillColor="{PRIMARY}"\n'
        f'        android:pathData="M0,0h{CANVAS:g}v{CANVAS:g}h-{CANVAS:g}z" />\n',
        CANVAS,
        "<!--\n  Recally launcher icon — background layer. Flat primary teal: no\n"
        "  gradient, no shadow. docs/design/design-system.md forbids elevation\n"
        "  outright, and this is the same colour as the app's primary action.\n-->"))

    factor = 24.0 / CANVAS
    (HERE / "ic_notification.xml").write_text(f"""<!--
  Recally notification icon. Android renders this as a flat silhouette and
  discards every colour, so it is white-on-transparent by construction.
  Same mark and gap as the launcher, rescaled to a 24dp viewport.

  Generated by docs/design/icon/build_icon.py.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24"
    android:tint="#FFFFFF">
{clipped_groups(rescale(path, factor), gap_top * factor, gap_bottom * factor, 24.0)}</vector>
""")

    (HERE / "ic_launcher.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@drawable/ic_launcher_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
        "</adaptive-icon>\n")

    print("  wrote 5 files")


if __name__ == "__main__":
    main()
